apps/adminPortal/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	#carrier register/login
	url(r'^login$', views.portal, name='admin_portal'),
	#admin login for full site stats
	url(r'^register_a$', views.RegisterA, name='registerA'),
	#carrier contact info
	url(r'^register/contact/info/(?P<company>\d+)/$', views.RegisterB, name='registerB'),
	#carrier shipping info
	url(r'^register/shipping/info/(?P<company>\d+)/$', views.RegisterC, name='registerC'),
	#carrier banking info /skip for now/
	url(r'^register/banking/info/(?P<company>\d+)/$', views.RegisterD, name='registerD'),
	#carrier registration review
	url(r'register/review/(?P<company>\d+)/$', views.RegisterReview, name='registerReview'),
	url(r'^admin_validate$', views.validateAdmin, name='admin_validate'),
	#forward register/login
	url(r'^login$', views.fportal, name='fadmin_portal'),
]

apps/carrier/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^business_dashboard/(?P<company>\d+)/$', views.Dash, name='dash'),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.logisite.urls', namespace='main')),
    url(r'^account/', include('apps.adminPortal.urls', namespace='account')),
    url(r'^carrier/', include('apps.carrier.urls', namespace='carrier')),
]

apps/adminPortal/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib import messages
import bcrypt
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')



# Create your models here.
class SubManager(models.Manager):
	#form part 1 : name, email, passwords, bcrypt
	def validateA(self, name, email, password, cpassword, request):
		try:
			check = SubCompany.objects.get(email=email)
			messages.warning(request, 'This email is already registered.')
			return false

		except:
		
			if len(name) < 1:
				messages.warning(request, 'Company Name Required.')
				return False
				
			if not EMAIL_REGEX.match(email):
				messages.warning(request, 'Invalid Email.')
				return False

			if len(password) < 8:
				messages.warning(request, 'Your password must contain at least 8 characters.')
				return False

			if password != cpassword:
				messages.warning(request, 'Your passwords do not match')
				return False

			password = password.encode()
			hashed = bcrypt.hashpw(password, bcrypt.gensalt())

			a = SubCompany(name=name, email=email, password = hashed)
			a.save()
			return a

	#form part 2 carrier contact information
	def validateB(self, id, fname, lname, phone, stradd, city, state, zipcode, request):
		
		if len(fname) < 1:
			messages.warning(request, 'First Name Required')
			return False
		if len(fname) > 0:
			if not fname.isalpha():
				messages.warning(request, 'First Name may only include alphabet characters.')
				return False
		if len(lname) < 1:
			messages.warning(request, 'Last Name Required')
			return False
		if len(lname) > 0:
			if not lname.isalpha():
				messages.warning(request, 'Last Name may only include alphabet characters.')
				return False
		if len(stradd) < 1:
			messages.warning(request, 'Street Address Required.')
			return False
		if len(state) < 1:
			messages.warning(request, 'State Required.')
			return False
		if len(zipcode) < 1:
			messages.warning(request, 'Zipcode Required.')
			return False

		a = SubCompany.objects.get(id=id)
		a.contact_fname = fname
		a.contact_lname = lname
		a.phone = phone
		a.street_address = stradd
		a.city = city
		a.state = state
		a.zipcode = zipcode
		a.save()
		return a

	# form part 3 Shippin Fee information
	def validateC(self, id, ftime, scharge, estop, fcharge, sdry, scold, zipcodes, request):
		#going to be the banking validation function
		count = 0
		ziplist = []
		z = ''
		for i in zipcodes:
			if i.isdigit():
				z+=i
				count+=1
			if count == 5:
				ziplist.append(z)
				count = 0
				z = ''

		print(ziplist)

		ftime = float(ftime)
		scharge = float(scharge)
		estop = float(estop)
		fcharge = float(fcharge)
		sdry = float(sdry)
		scold = float(scold)
		ftime = float(ftime)

		a = SubCompany.objects.get(id=id)


		a.free_time = ftime
		a.stop_charges = scharge
		a.exam_stop = estop
		a.fuel_surcharge = fcharge
		a.storage_dry = sdry
		a.storage_cold = scold
		a.save()
		for item in ziplist:
			try:
				check = Zips.objects.get(zipcode=item)
				a.zip_service.add(check)
			except:
				b = Zips(zipcode=item)
				b.save()
				a.zip_service.add(b)
			a.save()


		return a

	#form part 4 banking information /skipping for now/
	def validateD(self, ftime, scharge, estop, fcharge, sdry, scold, request):

		return






class User(models.Model):
	admin_email = models.CharField(max_length=50)
	password = models.CharField(max_length=200)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Zips(models.Model):
	zipcode = models.CharField(max_length=30, null=True, blank=True, unique=True)
	

class SubCompany(models.Model):
	name = models.CharField(max_length=60)
	email = models.CharField(max_length=50)
	password = models.CharField(max_length=200)
	phone = models.CharField(max_length = 20)
	location = models.CharField(max_length = 200)
	free_time = models.FloatField(null=True, blank=True, default=0.00)
	stop_charges = models.FloatField(null = True, blank = True, default = 0.00)
	exam_stop = models.FloatField(null = True, blank = True, default = 0.00)
	fuel_surcharge = models.FloatField(null = True, blank = True, default = 0.00)
	storage_dry = models.FloatField(null = True, blank = True, default = 0.00)
	storage_cold = models.FloatField(null = True, blank = True, default = 0.00)
	zip_service = models.ManyToManyField(Zips)
	drayage = models.FloatField(null=True, blank=True, default=0.00)
	contact_fname = models.CharField(max_length=40, default='', null=True)
	contact_lname = models.CharField(max_length=60, default='', null=True)
	street_address = models.CharField(max_length=200, null=True)
	state = models.CharField(max_length=40, null=True)
	zipcode = models.CharField(max_length=30, null=True)
	city = models.CharField(max_length=100, null=True)
	objects = SubManager()

apps/adminPortal/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from models import User, SubCompany, Zips
import json

# Create your views here.
def portal(request):
	return render(request, 'adminPortal/registerA.html')

def fportal(request):
	return render(request, 'adminPortal/fregisterA.html')

def validateAdmin(request):
	print(request.POST['userEmail'])
	try:
		a = User.objects.get(admin_email=request.POST['userEmail'])
	except:
		return redirect('main:index')
	if a.password == request.POST['userPassword']:
		print('******************')
	else:
		print('################')
	return redirect('account:b_dash')

# login or register page
def RegisterA(request):
	company = SubCompany.objects.validateA(name=request.POST['cname'], email=request.POST['cemail'], password=request.POST['cpass'], cpassword=request.POST['ccpass'], request=request)
	print('$$$$$$$$$$$', company)
	if company == False:
		return redirect('account:admin_portal')
	else:
		return redirect(reverse('account:registerB', args=(company.id,)))

# company information page
def RegisterB(request, company):
	a = SubCompany.objects.get(id=company)
	context = {'company':a.name, 'id':a.id}
	return render(request, 'adminPortal/registerB.html', context)

# shipping information page
def RegisterC(request, company):
	x = request.POST
	vComp = SubCompany.objects.validateB(id=company, fname=x['first_name'], lname=x['last_name'], phone=x['phone'], stradd=x['address'], city=x['city'], state=x['state'], zipcode=x['zip'], request=request)
	if vComp == False:
		a = SubCompany.objects.get(id=company)
		return redirect(reverse('account:registerB', args=(a.id,)))
	else:
		context = {'company':vComp.name, 'id':vComp.id}
		return render(request, 'adminPortal/registerC.html', context)

# bank accounts /skip for now/
def RegisterD(request, company):
	print('$$$$$$$',request.POST['zip'])
	a = SubCompany.objects.get(id=company)
	a.free_time = float(request.POST['free_time'])
	a.stop_charges = float(request.POST['stop_charges'])
	a.exam_stop = float(request.POST['exam_stop'])
	a.fuel_surcharge = float(request.POST['fuel_surcharge'])
	a.storage_dry = float(request.POST['storage_dry'])
	a.storage_cold = float(request.POST['storage_cold'])
	a.save()
	print(a.storage_cold)
	zips = request.POST['zip'].split()
	
	return redirect(reverse('account:registerC', args=(company.id,)))

def RegisterReview(request, company):
	print(request.POST['zip'])
	x = request.POST

	a = SubCompany.objects.validateC(id=company,ftime=x['free_time'],scharge=x['stop_charges'],estop=x['exam_stop'],fcharge=x['fuel_surcharge'],sdry=x['storage_dry'],scold=x['storage_cold'],zipcodes=x['zip'],request=request)

	# if we need to go back run this
	# return redirect(reverse('account:registerC', args=(a.id,)))
	return render(request, 'adminPortal/registerReview.html', {'company':a})

apps/adminPortal/templates/adminPortal/register.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>The Experts || Responsive HTML 5 Template</title> 

    <!-- mobile responsive meta -->
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/fav-icon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'images/fav-icon/favicon-32x32.png' %}" sizes="32x32">
    <link rel="icon" type="image/png" href="{% static 'images/fav-icon/favicon-16x16.png' %}" sizes="16x16">

</head>
<body>

<div class="boxed_wrapper">

<div class="inner-banner text-center">
    <div class="container">
        <div class="box">
            <h3>Admin Portal</h3>
        </div><!-- /.box -->
    </div><!-- /.container -->
</div>

<section class="register-section sec-padd-top">
    <div class="container">
        <div class="row">
            
            <!--Form Column-->
            <div class="form-column column col-sm-8 col-sm-offset-2">
            
                <div class="section-title">
                    <h3>Login Now</h3>
                    <div class="decor"></div>
                </div>
                
                <!--Login Form-->
                <div class="styled-form login-form">
                    <form method="post" action="{% url 'account:admin_validate' %}">
                    {% csrf_token %}
                        <div class="form-group">
                            <span class="adon-icon"><span class="fa fa-envelope-o"></span></span>
                            <input type="email" name="userEmail" value="" placeholder="Enter Email">
                        </div>
                        <div class="form-group">
                            <span class="adon-icon"><span class="fa fa-unlock-alt"></span></span>
                            <input type="password" name="userPassword" value="" placeholder="Enter Password">
                        </div>
                        <div class="clearfix">
                            <div class="form-group pull-left">
                                <button type="submit" class="thm-btn thm-tran-bg" value="submit" onclick="">login now</button>
                            </div>
                        </div>
                        
                    </form>
                </div>
                
            </div>
            
            <!--Form Column--> 
        </div>
    </div>
</section>

<footer class="main-footer">
     <!--Footer Bottom-->
     <section class="footer-bottom">
        <div class="container">
            <div class="pull-left copy-text">
                <p>Copyrights © 2017 All Rights Reserved. Powered by  <a href="/"> The Experts.</a></p>
                
            </div><!-- /.pull-right -->
        </div><!-- /.container -->
    </section>
     
</footer>

<!-- Scroll Top Button -->
    <button class="scroll-top tran3s color2_bg">
        <span class="fa fa-angle-up"></span>
    </button>
    <!-- pre loader  -->
    <div class="preloader"></div>


    <!-- jQuery js -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- jQuery ui js -->
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <!-- owl carousel js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- jQuery validation -->
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>

    <!-- mixit up -->
    <script src="{% static 'js/wow.js' %}"></script>
    <script src="{% static 'js/jquery.mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.fitvids.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'js/menuzord.js' %}"></script>

    <!-- revolution slider js -->
    <script src="{% static 'js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'js/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.actions.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.carousel.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.kenburn.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.layeranimation.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.migration.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.navigation.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.parallax.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.slideanims.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.video.min.js' %}"></script>

    <!-- fancy box -->
    <script src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
    <script src="{% static 'js/isotope.js' %}"></script>
    <script src="{% static 'js/jquery.polyglot.language.switcher.js' %}"></script>
    <script src="{% static 'js/nouislider.js' %}"></script>
    <script src="{% static 'js/jquery.bootstrap-touchspin.js' %}"></script>
    <script src="{% static 'js/SmoothScroll.js' %}"></script>
    <script src="{% static 'js/jquery.appear.js' %}"></script>
    <script src="{% static 'js/jquery.countTo.js' %}"></script>
    <script src="{% static 'js/jquery.flexslider.js' %}"></script>
    <script src="{% static 'js/imagezoom.js' %}"></script> 
    <script src="js/bxslider.js' %}"></script> 
    <script id="map-script" src="{% static 'js/default-map.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

</div>
    
</body>
</html>

apps/adminPortal/templates/adminPortal/registerC.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The Experts || Responsive HTML 5 Template</title> 

    {% load static %}
    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/fav-icon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'images/fav-icon/favicon-32x32.png' %}" sizes="32x32">
    <link rel="icon" type="image/png" href="{% static 'images/fav-icon/favicon-16x16.png' %}" sizes="16x16">

 

</head>
<body>

<div class="boxed_wrapper">


<div class="inner-banner text-center">
    <div class="container">
        <div class="box">
            <h3>Welcome, {{company.name}}</h3>
        </div><!-- /.box -->
        <div class="breadcumb-wrapper">
            <div class="clearfix">
                <div class="pull-left">
                    <ul class="list-inline link-list">
                        <li><a href="#">Company Information</a></li>
                        <li>Shipping Information<a href="#"></a></li>
                        <li><a href="#">Link Accounts</a></li>
                        <li style="color:black;">Review</li>
                    </ul>
                </div>
                <div class="pull-right">
                    <a href="#" class="get-qoute"><i class="fa fa-times"></i>Skip</a>
                </div><!-- /.pull-right -->
            </div><!-- /.container -->
        </div>
    </div><!-- /.container -->
</div>




<section class="register-section sec-padd-top">
    <div class="container">
        <div class="row">
            
            <!--Form Column-->
            <div class="form-column column col-md-12 col-sm-12 col-xs-12">
                
                <!--Login Form-->
                <div class="styled-form login-form">
                        <form class="well form-horizontal" action="{% url 'account:registerD' company.id %}" method="post"  id="contact_form">
                        {% csrf_token %}
                    <fieldset>

                    <!-- Form Name -->
                    <legend>Services</legend>

                    <!-- Text input-->

                    <div class="form-group">
                      <label class="col-md-4 control-label">Free Time</label>  
                      <div class="col-md-4 inputGroupContainer">
                      <div class="input-group">
                      <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                      <input  name="free_time" placeholder="00.00" class="form-control"  type="text">
                        </div>
                      </div>
                    </div>

                    <!-- Text input-->

                    <div class="form-group">
                      <label class="col-md-4 control-label" >Stop Charges</label> 
                        <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                      <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                      <input name="stop_charges" placeholder="00.00" class="form-control"  type="text">
                        </div>
                      </div>
                    </div>


                    <!-- Text input-->
                           
                    <div class="form-group">
                      <label class="col-md-4 control-label">Exam Stop</label>  
                        <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                      <input name="exam_stop" placeholder="00.00" class="form-control" type="text">
                        </div>
                      </div>
                    </div>

                    <!-- Text input-->
                          
                    <div class="form-group">
                      <label class="col-md-4 control-label">Fuel Surcharge</label>  
                        <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                      <input name="fuel_surcharge" placeholder="00.00" class="form-control" type="text">
                        </div>
                      </div>
                    </div>

                    <!-- Text input-->
                     
                    <div class="form-group">
                      <label class="col-md-4 control-label">Storage Dry</label>  
                        <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                      <input name="storage_dry" placeholder="00.00" class="form-control"  type="text">
                        </div>
                      </div>
                    </div>

                    <!-- Select Basic -->
                       
                    <div class="form-group"> 
                      <label class="col-md-4 control-label">Storage Cold</label>
                        <div class="col-md-4 selectContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                       <input name="storage_cold" placeholder="00.00" class="form-control"  type="text">
                      </div>
                    </div>
                    </div>

                    <!-- Text input-->

                    <div class="form-group">
                      <label class="col-md-4 control-label">Zip Codes Serviced (seperate by spaces only)</label>  
                        <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-truck"></i></span>
                      <input name="zip" placeholder="90038 90039 90040" class="form-control"  type="text">
                        </div>
                    </div>
                    </div>


                    <!-- Button -->
                    <div class="form-group">
                      <label class="col-md-4 control-label"></label>
                      <div class="col-md-4">
                        <button type="submit" class="btn btn-primary" >Next</button>
                      </div>
                    </div>

                </fieldset>
                </form>
                </div>
                
            </div>
            
        </div>
    </div>
</section>


     <!--Footer Bottom-->
     <section class="footer-bottom">
        <div class="container">
            <div class="pull-left copy-text">
                <p>Copyrights © 2017 All Rights Reserved. Powered by  <a href="#"> Connectly.</a></p>
                
            </div><!-- /.pull-right -->
            <div class="pull-right get-text">
                <ul>
                    <li><a href="#">Support |  </a></li>
                    <li><a href="#">Privacy &amp; Policy |</a></li>
                    <li><a href="#"> Terms &amp; Conditions</a></li>
                </ul>
            </div><!-- /.pull-left -->
        </div><!-- /.container -->
    </section>
     
</footer>

<!-- Scroll Top Button -->

    <!-- pre loader  -->
    <div class="preloader"></div>


    <!-- jQuery js -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- jQuery ui js -->
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <!-- owl carousel js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- jQuery validation -->
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>

    <!-- mixit up -->
    <script src="{% static 'js/wow.js' %}"></script>
    <script src="{% static 'js/jquery.mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.fitvids.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'js/menuzord.js' %}"></script>

    <!-- revolution slider js -->
    <script src="{% static 'js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'js/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.actions.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.carousel.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.kenburn.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.layeranimation.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.migration.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.navigation.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.parallax.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.slideanims.min.js' %}"></script>
    <script src="{% static 'js/revolution.extension.video.min.js' %}"></script>

    <!-- fancy box -->
    <script src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
    <script src="{% static 'js/isotope.js' %}"></script>
    <script src="{% static 'js/jquery.polyglot.language.switcher.js' %}"></script>
    <script src="{% static 'js/nouislider.js' %}"></script>
    <script src="{% static 'js/jquery.bootstrap-touchspin.js' %}"></script>
    <script src="{% static 'js/SmoothScroll.js' %}"></script>
    <script src="{% static 'js/jquery.appear.js' %}"></script>
    <script src="{% static 'js/jquery.countTo.js' %}"></script>
    <script src="{% static 'js/jquery.flexslider.js' %}"></script>
    <script src="{% static 'js/imagezoom.js' %}"></script> 
    <script src="{% static 'js/bxslider.js' %}"></script> 
    <script id="map-script" src="{% static 'js/default-map.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

</div>
    
</body>
</html>